---
# handlers file for OULibraries.zabbix
- name: Import Zabbix schema
  mysql_db:
    name: "{{ zabbix_db}}"
    target: "/usr/share/doc/zabbix-server-mysql-3.0.2/create.sql.gz"
    state: import
    login_user: "{{mariadb_root_user}}"
    login_password: "root"
    login_host: "{{mariadb_host}}"


- name: Restart Zabbix server
  service:
    name: zabbix-server
    state: restarted

- name: Restart Zabbix web
  service:
    name: httpd
    state: restarted
